# If you add a page, you must add it to the index here
pages:
  - Home: 'index.md'
  - Getting Started:
    - Getting Started With Scripts: 'Getting_Started.md'
  - Commands:
    - Commands: 'Vanilla/Commands.md'
  - Brackets:
    - Bracket Handlers: 'Brackets/Brackets.md'
  - Item States:
    - Item Conditions: 'Vanilla/Item_Modification/Item_Conditions.md'
  - Recipes:
    - Vanilla:
      - Brackets:
        - Items: 'Vanilla/Brackets/Bracket_Item.md'
      - Recipes:
        - Crafting Table Recipes: 'Vanilla/Recipes/Recipes_Crafting_Table.md'
        - Furnace Recipes: 'Vanilla/Recipes/Recipes_Furnace.md'
  - Ore Dictionary:
    - Ore Dictionary: 'Vanilla/OreDic.md'
  - Advanced Functions:
    - Arrays and Loops: 'AdvancedFunctions/Arrays_and_Loops.md'
    - Calculations: 'AdvancedFunctions/Calculations.md'
    - Contional Statements: 'AdvancedFunctions/Conditional_Statements.md'
    - Custom Functions: 'AdvancedFunctions/Custom_Functions.md'
    - Import: 'AdvancedFunctions/Import.md'
    - Variable Types: 'AdvancedFunctions/Variable_Types.md'

# Do not edit in PRs below here
site_name: Crafttweaker Documentation

markdown_extensions:
  - admonition
  - smarty
  - sane_lists

theme: readthedocs