# If you add a page, you must add it to the index here
pages:
  - Home: 'index.md'
  - Getting Started With Scripts: 'Getting_Started.md'
  - Commands: 'Vanilla/Commands.md'
  - CTGUI: 'Vanilla/CTGUI.md'
  - Bracket Handlers: 'Brackets/Brackets.md'
  - Ore Dictionary: 'Vanilla/OreDict.md'
  - Advanced Functions:
    - Arrays and Loops: 'AdvancedFunctions/Arrays_and_Loops.md'
    - Calculations: 'AdvancedFunctions/Calculations.md'
    - Conditional Statements: 'AdvancedFunctions/Conditional_Statements.md'
    - Custom Functions: 'AdvancedFunctions/Custom_Functions.md'
    - Import: 'AdvancedFunctions/Import.md'
    - Recipe Functions: 'AdvancedFunctions/Recipe_Functions.md'
    - Preprocessors:
      - On Preprocessors: 'AdvancedFunctions/Preprocessors/On_Preprocessors.md'
      - Debug: 'AdvancedFunctions/Preprocessors/DebugPreprocessor.md'
      - Ignore Bracket Errors: 'AdvancedFunctions/Preprocessors/IgnoreBracketErrorPreprocessor.md'
      - Loader: 'AdvancedFunctions/Preprocessors/LoaderPreprocessor.md'
      - Mod Loaded: 'AdvancedFunctions/Preprocessors/ModLoadedPreprocessor.md'
      - No Run: 'AdvancedFunctions/Preprocessors/NoRunPreprocessor.md'
      - Priority: 'AdvancedFunctions/Preprocessors/PriorityPreprocessor.md'
  - Tips and Tricks:
      - Foreword: 'Tips_Tricks/Foreword.md'
      - Items:
        - Using IItemDefinitions for meta ranges: 'Tips_Tricks/Items/IItemDefinition_Metas.md'
      - General Tips:
        - Split your scripts into multiple files: 'Tips_Tricks/General/Split_Files.md'
        - Use Loops to make your scripts easier to read: 'Tips_Tricks/General/Loops_Readability.md'
  - Vanilla:
    - Biomes:
      - IBiome: 'Vanilla/Biomes/IBiome.md'
    - Blocks:
      - IBlock: 'Vanilla/Blocks/IBlock.md'
      - IBlockDefinition: 'Vanilla/Blocks/IBlockDefinition.md'
      - IBlockPattern: 'Vanilla/Blocks/IBlockPattern.md'
    - Brackets:
      - Items: 'Vanilla/Brackets/Bracket_Item.md'
      - Entities: 'Vanilla/Brackets/Bracket_Entity.md'
      - Liquids: 'Vanilla/Brackets/Bracket_Liquid.md'
      - Ores: 'Vanilla/Brackets/Bracket_Ore.md'
      - Potions: 'Vanilla/Brackets/Bracket_Potion.md'
    - Entities:
      - IEntityDefinition: 'Vanilla/Entities/IEntityDefinition.md'
      - IEntityDrop: 'Vanilla/Entities/IEntityDrop.md'
    - Game:
      - IClient: 'Vanilla/Game/IClient.md'
      - IGame: 'Vanilla/Game/IGame.md'
      - IPlayer: 'Vanilla/Game/IPlayer.md'
      - Mods: 'Vanilla/Game/Mods.md'
    - Items:
      - IItemDefinition: 'Vanilla/Items/IItemDefinition.md'
      - IItemStack: 'Vanilla/Items/IItemStack.md'
      - Item Conditions: 'Vanilla/Items/Item_Conditions.md'
      - Item Transformers: 'Vanilla/Items/Item_Transformers.md'
      - Tooltips: 'Vanilla/Items/Tooltips.md'
      - Renaming: 'Vanilla/Items/Renaming.md'
      - Weighted ItemStack: 'Vanilla/Items/WeightedItemStack.md'
    - Liquids:
      - ILiquidStack: 'Vanilla/Liquids/ILiquidStack.md'
      - ILiquidDefinition: 'Vanilla/Liquids/ILiquidDefinition.md'
    - Potions:
      - IPotion: 'Vanilla/Potions/IPotion.md'
    - Recipes:
      - Crafting Table Recipes: 'Vanilla/Recipes/Recipes_Crafting_Table.md'
      - Furnace Recipes: 'Vanilla/Recipes/Recipes_Furnace.md'
      - Seed Drops: 'Vanilla/Recipes/Seeds.md'
    - Utils:
      - ItemUtils: 'Vanilla/Utils/IItemUtils.md'
      - Position3f: 'Vanilla/Utils/Position3f.md'
    - Variable Types:
      - Types Overview: 'Vanilla/Variable_Types/Variable_Types.md'
      - Basic Variable Functions: 'Vanilla/Variable_Types/Basic_Variables_Functions.md'
      - IIngredient: 'Vanilla/Variable_Types/IIngredient.md'
  - Mods:
    - Astral Sorcery:
      - About Astral Sorcery: 'Mods/Astral_Sorcery/Astral_Sorcery.md'
      - Crafting:
        - Altar: 'Mods/Astral_Sorcery/Altar.md'
        - Light-Well: 'Mods/Astral_Sorcery/Well.md'
        - Ritual Mineralis: 'Mods/Astral_Sorcery/Ritual_Mineralis.md'
        - Starlight Infusion: 'Mods/Astral_Sorcery/Infusion.md'
        - Starlight Transmutation: 'Mods/Astral_Sorcery/Transmutation.md'
    - ContentTweaker:
      - ContentTweaker: 'Mods/ContentTweaker/ContentTweaker.md'
      - Commands: 'Mods/ContentTweaker/Commands.md'
      - WalkThrough: 'Mods/ContentTweaker/WalkThrough.md'
      - Vanilla:
        - Brackets:
          - Block Material: 'Mods/ContentTweaker/Vanilla/Brackets/Bracket_Block_Material.md'
          - Blocks: 'Mods/ContentTweaker/Vanilla/Brackets/Bracket_Blocks.md'
          - Creative Tab: 'Mods/ContentTweaker/Vanilla/Brackets/Bracket_Creative_Tab.md'
          - SoundType: 'Mods/ContentTweaker/Vanilla/Brackets/Bracket_Sound_Type.md'
          - SoundEvent: 'Mods/ContentTweaker/Vanilla/Brackets/Bracket_Sound_Event.md'
        - Creatable Content:
          - Vanilla Factory: 'Mods/ContentTweaker/Vanilla/Creatable_Content/VanillaFactory.md'
          - Block: 'Mods/ContentTweaker/Vanilla/Creatable_Content/Block.md'
          - Creative Tab: 'Mods/ContentTweaker/Vanilla/Creatable_Content/Creative_Tab.md'
          - Fluid: 'Mods/ContentTweaker/Vanilla/Creatable_Content/Fluid.md'
          - Item: 'Mods/ContentTweaker/Vanilla/Creatable_Content/Item.md'
        - Advanced Functionality: 
          - Commands: 'Mods/ContentTweaker/Vanilla/Advanced_Functionality/Commands.md'
          - Functions: 
            - ActionResult: 'Mods/ContentTweaker/Vanilla/Advanced_Functionality/Functions/ActionResult.md'
            - IBlockAction: 'Mods/ContentTweaker/Vanilla/Advanced_Functionality/Functions/IBlockAction.md'
            - IItemRightClick: 'Mods/ContentTweaker/Vanilla/Advanced_Functionality/Functions/IItemRightClick.md'
            - IItemUse: 'Mods/ContentTweaker/Vanilla/Advanced_Functionality/Functions/IItemUse.md'
        - Types:
          - Block:
            - Facing: 'Mods/ContentTweaker/Vanilla/Types/Block/Facing.md'
            - ICTBlockState: 'Mods/ContentTweaker/Vanilla/Types/Block/ICTBlockState.md'
            - IBlockPos: 'Mods/ContentTweaker/Vanilla/Types/Block/IBlockPos.md'
            - IMaterialDefinition: 'Mods/ContentTweaker/Vanilla/Types/Block/IMaterialDefinition.md'
            - MCAxisAlignedBB: 'Mods/ContentTweaker/Vanilla/Types/Block/MCAxisAlignedBB.md'
          - Item:
            - IMutableItemStack: 'Mods/ContentTweaker/Vanilla/Types/Item/IMutableItemStack.md'
          - Player:
            - Hand: 'Mods/ContentTweaker/Vanilla/Types/Player/Hand.md'
            - ICTPlayer: 'Mods/ContentTweaker/Vanilla/Types/Player/ICTPlayer.md'
          - Sound:
            - ISoundTypeDefinition: 'Mods/ContentTweaker/Vanilla/Types/Sound/ISoundTypeDefinition.md'
            - ISoundEventDefinition: 'Mods/ContentTweaker/Vanilla/Types/Sound/ISoundEventDefinition.md'
          - World:
            - IWorld: 'Mods/ContentTweaker/Vanilla/Types/World/IWorld.md'
      - Material System:
        - Introduction: 'Mods/ContentTweaker/Materials/Introduction.md'
        - MaterialSystem: 'Mods/ContentTweaker/Materials/MaterialSystem.md'
        - Brackets:
          - Material Part Bracket Handler: 'Mods/ContentTweaker/Materials/Brackets/Bracket_MaterialPart.md'
        - Materials:
          - Material: 'Mods/ContentTweaker/Materials/Materials/Material.md'
          - Material Builder: 'Mods/ContentTweaker/Materials/Materials/Material_Builder.md'
          - Material Part: 'Mods/ContentTweaker/Materials/Materials/MaterialPart.md'
          - Material Part Data: 'Mods/ContentTweaker/Materials/Materials/MaterialPartData.md'
        - Parts:
          - Part: 'Mods/ContentTweaker/Materials/Parts/Part.md'
          - Part Builder: 'Mods/ContentTweaker/Materials/Parts/Part_Builder.md'
          - PartType: 'Mods/ContentTweaker/Materials/Parts/PartType.md'
          - PartDataPiece: 'Mods/ContentTweaker/Materials/Parts/PartDataPiece.md'
    - JEI:
      - JEI: 'Mods/JEI/JEI.md'
    - Mekanism:
      - Chemical Crystallizer: 'Mods/Mekanism/Chemical_Crystallizer.md'
      - Chemical Dissolution Chamber: 'Mods/Mekanism/Chemical_Dissolution_Chamber.md'
      - Chemical Infuser: 'Mods/Mekanism/Chemical_Infuser.md'
      - Chemical Injection Chamber: 'Mods/Mekanism/Chemical_Injection_Chamber.md'
      - Chemical Oxidizer: 'Mods/Mekanism/Chemical_Oxidizer.md'
      - Chemical Washer: 'Mods/Mekanism/Chemical_Washer.md'
      - Combiner: 'Mods/Mekanism/Combiner.md'
      - Crusher: 'Mods/Mekanism/Crusher.md'
      - Electrolytic Separator: 'Mods/Mekanism/Electrolytic_Separator.md'
      - Energized Smelter: 'Mods/Mekanism/Energized_Smelter.md'
      - Enrichment Chamber: 'Mods/Mekanism/Enrichment_Chamber.md'
      - Gas: 'Mods/Mekanism/Gas.md'
      - Metallurgic Infuser: 'Mods/Mekanism/Metallurgic_Infuser.md'
      - Osmium Compressor: 'Mods/Mekanism/Osmium_Compressor.md'
      - Precision Sawmill: 'Mods/Mekanism/Precision_Sawmill.md'
      - Pressurised Reaction Chamber: 'Mods/Mekanism/Pressurised_Reaction_Chamber.md'
      - Purification Chamber: 'Mods/Mekanism/Purification_Chamber.md'
      - Solar Neutron Activator: 'Mods/Mekanism/Solar_Neutron_Activator.md'
      - Thermal Evaporation: 'Mods/Mekanism/Thermal_Evaporation.md'
    - Modtweaker:
      - Modtweaker: 'Mods/Modtweaker/Modtweaker.md'
      - Actually Additions:
        - Atomic Reconstructor: 'Mods/Modtweaker/ActuallyAdditions/AtomicReconstructor.md'
        - Ball of Fur: 'Mods/Modtweaker/ActuallyAdditions/BallOfFur.md'
        - Compost: 'Mods/Modtweaker/ActuallyAdditions/Compost.md'
        - Crusher: 'Mods/Modtweaker/ActuallyAdditions/Crusher.md'
        - Empowerer: 'Mods/Modtweaker/ActuallyAdditions/Empowerer.md'
        - Treasure Chest: 'Mods/Modtweaker/ActuallyAdditions/TreasureChest.md'
      - BetterWithMods:
        - Anvil: 'Mods/Modtweaker/BetterWithMods/Anvil.md'
        - Buoyancy: 'Mods/Modtweaker/BetterWithMods/Buoyancy.md'
        - Cauldron: 'Mods/Modtweaker/BetterWithMods/Cauldron.md'
        - Stoked Cauldron: 'Mods/Modtweaker/BetterWithMods/StokedCauldron.md'
        - Crucible: 'Mods/Modtweaker/BetterWithMods/Crucible.md'
        - Stoked Crucible: 'Mods/Modtweaker/BetterWithMods/StokedCrucible.md'
        - Kiln: 'Mods/Modtweaker/BetterWithMods/Kiln.md'
        - Saw: 'Mods/Modtweaker/BetterWithMods/Saw.md'
        - Turntable: 'Mods/Modtweaker/BetterWithMods/Turntable.md'
        - HCMovement: 'Mods/Modtweaker/BetterWithMods/HCMovement.md'
      - Extra Utilities 2:
        - Crusher: 'Mods/Modtweaker/Extra_Utilities_2/Crusher.md'
        - Resonator: 'Mods/Modtweaker/Extra_Utilities_2/Resonator.md'
      - Forestry:
        - Carpenter: 'Mods/Modtweaker/Forestry/Carpenter.md'
        - Centrifuge: 'Mods/Modtweaker/Forestry/Centrifuge.md'
        - Fermenter: 'Mods/Modtweaker/Forestry/Fermenter.md'
        - Moistener: 'Mods/Modtweaker/Forestry/Moistener.md'
        - Squeezer: 'Mods/Modtweaker/Forestry/Squeezer.md'
        - Still: 'Mods/Modtweaker/Forestry/Still.md'
        - Thermionic Fabricator: 'Mods/Modtweaker/Forestry/Thermionic_Fabricator.md'
      - Tinkers' Construct:
        - Alloying: 'Mods/Modtweaker/TConstruct/Alloying.md'
        - Casting: 'Mods/Modtweaker/TConstruct/Casting.md'
        - Drying: 'Mods/Modtweaker/TConstruct/Drying.md'
        - Melting: 'Mods/Modtweaker/TConstruct/Melting.md'
        - Smeltery Fuel: 'Mods/Modtweaker/TConstruct/Fuel.md'
      - Thermal Expansion:
        - Centrifugal Seperator: 'Mods/Modtweaker/ThermalExpansion/Centrifugal_Seperator.md'
        - Compactor: 'Mods/Modtweaker/ThermalExpansion/Compactor.md'
        - Crucible: 'Mods/Modtweaker/ThermalExpansion/Crucible.md'
        - Energetic Infuser: 'Mods/Modtweaker/ThermalExpansion/Energetic_Infuser.md'
        - Fluid Transposer: 'Mods/Modtweaker/ThermalExpansion/Fluid_Transposer.md'
        - InductionSmelter: 'Mods/Modtweaker/ThermalExpansion/InductionSmelter.md'
        - Insolator: 'Mods/Modtweaker/ThermalExpansion/Insolator.md'
        - Pulverizer: 'Mods/Modtweaker/ThermalExpansion/Pulverizer.md'
        - Redstone Furnace: 'Mods/Modtweaker/ThermalExpansion/Redstone_Furnace.md'
        - Refinery: 'Mods/Modtweaker/ThermalExpansion/Refinery.md'
        - Sawmill: 'Mods/Modtweaker/ThermalExpansion/Sawmill.md'
    - Industrial Foregoing:
      - Industrial Foregoing: 'Mods/IndustrialForegoing/IndustrialForegoing.md'
      - BioReactor: 'Mods/IndustrialForegoing/BioReactor.md'
      - Laser Drill: 'Mods/IndustrialForegoing/LaserDrill.md'
      - Sludge Refiner: 'Mods/IndustrialForegoing/SludgeRefiner.md'
    - PackMode:
      - PackMode: 'Mods/Pack_Mode/Packmode.md'
      - Preprocessor: 'Mods/Pack_Mode/Preprocessors/Preprocessor_Packmode.md'
      - Command: 'Mods/Pack_Mode/Commands/Packmode_Command.md'


# Do not edit in PRs below here
site_name: Crafttweaker Documentation

markdown_extensions:
  - admonition
  - smarty
  - sane_lists

theme_dir: 'mkdocs_windmill'

extra:
  logo: 'assets/logo.png'
  #version: 0.0
  #article_nav_top: true
  #artivle_nav_bottom: true
  #history_buttons: false
