# If you add a page, you must add it to the index here
pages:
  - Home: 'index.md'
  - Getting Started:
    - Getting Started With Scripts: 'Getting_Started.md'
  - Commands:
    - Commands: 'Vanilla/Commands.md'
  - Brackets:
    - Bracket Handlers: 'Brackets/Brackets.md'
  - Ore Dictionary:
    - Ore Dictionary: 'Vanilla/OreDict.md'
  - Advanced Functions:
    - Arrays and Loops: 'AdvancedFunctions/Arrays_and_Loops.md'
    - Calculations: 'AdvancedFunctions/Calculations.md'
    - Conditional Statements: 'AdvancedFunctions/Conditional_Statements.md'
    - Custom Functions: 'AdvancedFunctions/Custom_Functions.md'
    - Import: 'AdvancedFunctions/Import.md'
    - Recipe Functions: 'AdvancedFunctions/Recipe_Functions.md'
    - Preprocessors:
      - On Preprocessors: 'AdvancedFunctions/Preprocessors/On_Preprocessors.md'
      - Debug: 'AdvancedFunctions/Preprocessors/DebugPreprocessor.md'
      - Ignore Bracket Errors: 'AdvancedFunctions/Preprocessors/IgnoreBracketErrorPreprocessor.md'
      - Loader: 'AdvancedFunctions/Preprocessors/LoaderPreprocessor.md'
      - Mod Loaded: 'AdvancedFunctions/Preprocessors/ModLoadedPreprocessor.md'
      - No Run: 'AdvancedFunctions/Preprocessors/NoRunPreprocessor.md'
      - Priority: 'AdvancedFunctions/Preprocessors/PriorityPreprocessor.md'
  - Tips and Tricks:
      - Foreword: 'Tips_Tricks/Foreword.md'
      - Items:
        - Using IItemDefinitions for meta ranges: 'Tips_Tricks/Items/IItemDefinition_Metas.md'
      - General Tips:
        - Split your scripts into multiple files: 'Tips_Tricks/General/Split_Files.md'
        - Use Loops to make your scripts easier to read: 'Tips_Tricks/General/Loops_Readability.md'
  - Vanilla:
    - Blocks:
      - IBlock: 'Vanilla/Blocks/IBlock.md'
      - IBlockDefinition: 'Vanilla/Blocks/IBlockDefinition.md'
      - IBlockPattern: 'Vanilla/Blocks/IBlockPattern.md'
    - Brackets:
      - Items: 'Vanilla/Brackets/Bracket_Item.md'
      - Entities: 'Vanilla/Brackets/Bracket_Entity.md'
      - Liquids: 'Vanilla/Brackets/Bracket_Liquid.md'
      - Ores: 'Vanilla/Brackets/Bracket_Ore.md'
      - Potions: 'Vanilla/Brackets/Bracket_Potion.md'
    - Entities:
      - IEntityDefinition: 'Vanilla/Entities/IEntityDefinition.md'
      - IEntityDrop: 'Vanilla/Entities/IEntityDrop.md'
    - Game:
      - IClient: 'Vanilla/Game/IClient.md'
      - IGame: 'Vanilla/Game/IGame.md'
      - IItemUtils : 'Vanilla/Game/IItemUtils.md'
      - IPlayer: 'Vanilla/Game/IPlayer.md'
      - Mods: 'Vanilla/Game/Mods.md'
    - Items:
      - IItemDefinition: 'Vanilla/Items/IItemDefinition.md'
      - IItemStack: 'Vanilla/Items/IItemStack.md'
      - Item Conditions: 'Vanilla/Items/Item_Conditions.md'
      - Item Transformers: 'Vanilla/Items/Item_Transformers.md'
      - Tooltips: 'Vanilla/Items/Tooltips.md'
      - Renaming: 'Vanilla/Items/Renaming.md'
    - Liquids:
      - ILiquidStack: 'Vanilla/Liquids/ILiquidStack.md'
      - ILiquidDefinition: 'Vanilla/Liquids/ILiquidDefinition.md'
    - Potions:
      - IPotion: 'Vanilla/Potions/IPotion.md'
    - Recipes:
      - Crafting Table Recipes: 'Vanilla/Recipes/Recipes_Crafting_Table.md'
      - Furnace Recipes: 'Vanilla/Recipes/Recipes_Furnace.md'
      - Seed Drops: 'Vanilla/Recipes/Seeds.md'
    - Variable Types:
      - Types Overview: 'Vanilla/Variable_Types/Variable_Types.md'
      - Basic Variable Functions: 'Vanilla/Variable_Types/Basic_Variables_Functions.md'
      - IIngredient: 'Vanilla/Variable_Types/IIngredient.md'
  - Mods:
    - Modtweaker:
      - Modtweaker: 'Mods/Modtweaker/Modtweaker.md'
      - Actually Additions:
        - AtomicReconstructor: 'Mods/Modtweaker/ActuallyAdditions/AtomicReconstructor.md'
        - BallOfFur: 'Mods/Modtweaker/ActuallyAdditions/BallOfFur.md'
        - Compost: 'Mods/Modtweaker/ActuallyAdditions/Compost.md'
        - Crusher: 'Mods/Modtweaker/ActuallyAdditions/Crusher.md'
        - Empowerer: 'Mods/Modtweaker/ActuallyAdditions/Empowerer.md'
        - TreasureChest: 'Mods/Modtweaker/ActuallyAdditions/TreasureChest.md'
      - BetterWithMods:
        - Anvil: 'Mods/Modtweaker/BetterWithMods/Anvil.md'
        - Buoyancy: 'Mods/Modtweaker/BetterWithMods/Buoyancy.md'
        - Cauldron: 'Mods/Modtweaker/BetterWithMods/Cauldron.md'
        - Stoked Cauldron: 'Mods/Modtweaker/BetterWithMods/StokedCauldron.md'
        - Crucible: 'Mods/Modtweaker/BetterWithMods/Crucible.md'
        - Stoked Crucible: 'Mods/Modtweaker/BetterWithMods/StokedCrucible.md'
        - Kiln: 'Mods/Modtweaker/BetterWithMods/Kiln.md'
        - Saw: 'Mods/Modtweaker/BetterWithMods/Saw.md'
        - Turntable: 'Mods/Modtweaker/BetterWithMods/Turntable.md'
        - HCMovement: 'Mods/Modtweaker/BetterWithMods/HCMovement.md'
      - JEI:
        - JEI: 'Mods/JEI/JEI.md'
      - Thermal Expansion:
        - Compactor: 'Mods/Modtweaker/ThermalExpansion/Compactor.md'
        - Crucible: 'Mods/Modtweaker/ThermalExpansion/Crucible.md'
        - InductionSmelter: 'Mods/Modtweaker/ThermalExpansion/InductionSmelter.md'
        - Insolator: 'Mods/Modtweaker/ThermalExpansion/Insolator.md'
        - Pulverizer: 'Mods/Modtweaker/ThermalExpansion/Pulverizer.md'
        - Refinery: 'Mods/Modtweaker/ThermalExpansion/Refinery.md'
        - Sawmill: 'Mods/Modtweaker/ThermalExpansion/Sawmill.md'



# Do not edit in PRs below here
site_name: Crafttweaker Documentation

markdown_extensions:
  - admonition
  - smarty
  - sane_lists

theme: windmill