- Vanilla:
    - Api:
      - BracketHandlers: 'vanilla/api/BracketHandlers.md'
      - Blocco:
        - Materiale:
          - MCMaterial: 'vanilla/api/block/material/MCMaterial.md'
      - Blocchi:
        - MCBlock: 'vanilla/api/blocks/MCBlock.md'
        - MCBlockState: 'vanilla/api/blocks/MCBlockState.md'
      - Parentesi
        - CommandStringDisplayable: 'vanilla/api/brackets/CommandStringDisplayable.md'
      - Comandi:
        - Personalizzato:
          - CustomCommands: 'vanilla/api/commands/custom/CustomCommands.md'
          - MCAmbiguityConsumer: 'vanilla/api/commands/custom/MCAmbiguityConsumer.md'
          - MCArgumentBuilder: 'vanilla/api/commands/custom/MCArgumentBuilder.md'
          - MCArgumentCommandNode: 'vanilla/api/commands/custom/MCArgumentCommandNode.md'
          - MCCommand: 'vanilla/api/commands/custom/MCCommand.md'
          - MCCommandContext: 'vanilla/api/commands/custom/MCCommandContext.md'
          - MCCommandContextBuilder: 'vanilla/api/commands/custom/MCCommandContextBuilder.md'
          - MCCommandDispatcher: 'vanilla/api/commands/custom/MCCommandDispatcher.md'
          - MCCommandNode: 'vanilla/api/commands/custom/MCCommandNode.md'
          - MCCommandSource: 'vanilla/api/commands/custom/MCCommandSource.md'
          - MCImmutableStringReader: 'vanilla/api/commands/custom/MCImmutableStringReader.md'
          - MCLiteralArgumentBuilder: 'vanilla/api/commands/custom/MCLiteralArgumentBuilder.md'
          - MCLiteralCommandNode: 'vanilla/api/commands/custom/MCLiteralCommandNode.md'
          - MCParseRisultati: 'vanilla/api/commands/custom/MCParseResults.md'
          - MCParsedArgument: 'vanilla/api/commands/custom/MCParsedArgument.md'
          - MCParsedCommandNode: 'vanilla/api/commands/custom/MCParsedCommandNode.md'
          - MCRedirectModifier: 'vanilla/api/commands/custom/MCRedirectModifier.md'
          - MCRequiredArgumentBuilder: 'vanilla/api/commands/custom/MCRequiredArgumentBuilder.md'
          - MCResultConsumer: 'vanilla/api/commands/custom/MCResultConsumer.md'
          - MCRootCommandNode: 'vanilla/api/commands/custom/MCRootCommandNode.md'
          - MCSingleRedirectModifier: 'vanilla/api/commands/custom/MCSingleRedirectModifier.md'
          - MCStringRange: 'vanilla/api/commands/custom/MCStringRange.md'
          - MCSuggestion: 'vanilla/api/commands/custom/MCSuggestion.md'
          - MCSuggestionContext: 'vanilla/api/commands/custom/MCSuggestionContext.md'
          - MCSuggestionProvider: 'vanilla/api/commands/custom/MCSuggestionProvider.md'
          - MCSuggestions: 'vanilla/api/commands/custom/MCSuggestions.md'
          - MCSuggestionsBuilder: 'vanilla/api/commands/custom/MCSuggestionsBuilder.md'
      - Dati:
        - ByteArrayData: 'vanilla/api/data/ByteArrayData.md'
        - ByteData: 'vanilla/api/data/ByteData.md'
        - DoubleData: 'vanilla/api/data/DoubleData.md'
        - FloatData: 'vanilla/api/data/FloatData.md'
        - ICollectionDati: 'vanilla/api/data/ICollectionData.md'
        - IData: 'vanilla/api/data/IData.md'
        - INumberData: 'vanilla/api/data/INumberData.md'
        - IntArrayData: 'vanilla/api/data/IntArrayData.md'
        - IntData: 'vanilla/api/data/IntData.md'
        - ListData: 'vanilla/api/data/ListData.md'
        - LongArrayData: 'vanilla/api/data/LongArrayData.md'
        - LongData: 'vanilla/api/data/LongData.md'
        - MapData: 'vanilla/api/data/MapData.md'
        - ShortData: 'vanilla/api/data/ShortData.md'
        - StringData: 'vanilla/api/data/StringData.md'
      - Entit√†:
        - MCEntityClassification: 'vanilla/api/entities/MCEntityClassification.md'
        - MCEntityType: 'vanilla/api/entities/MCEntityType.md'
      - Fluido:
        - IFluidStack: 'vanilla/api/fluido/IFluidStack.md'
        - MCFluid: 'vanilla/api/fluido/MCFluid.md'
      - Cibo:
        - MCFood: 'vanilla/api/food/MCFood.md'
      - Articoli:
        - IIngrediente: 'vanilla/api/items/IIngredient.md'
        - IIngredientTransformer: 'vanilla/api/items/IIngredientTransformer.md'
        - IIngredientTransformer: 'vanilla/api/items/IIngredientTransformer.md'
        - IItemStack: 'vanilla/api/items/IItemStack.md'
        - Elenco Ingredienti: 'vanilla/api/items/IngredientList.md'
        - MCIngredientConditioned: 'vanilla/api/items/MCIngredientConditioned.md'
        - MCIngredientTransformed: 'vanilla/api/items/MCIngredientTransformed.md'
        - MCWeightedItemStack: 'vanilla/api/items/MCWeightedItemStack.md'
      - Logger:
        - ILogger: 'vanilla/api/logger/ILogger.md'
      - Dirigenti:
        - BlastFurnaceManager: 'vanilla/api/managers/BlastFurnaceManager.md'
        - CampFireManager: 'vanilla/api/managers/CampFireManager.md'
        - CraftingTableManager: 'vanilla/api/managers/CraftingTableManager.md'
        - FurnaceManager: 'vanilla/api/managers/FurnaceManager.md'
        - ICookingRecipeManager: 'vanilla/api/managers/ICookingRecipeManager.md'
        - IRecipeManager: 'vanilla/api/managers/IRecipeManager.md'
        - SmithingManager: 'vanilla/api/managers/SmithingManager.md'
        - SmokerManager: 'vanilla/api/managers/SmokerManager.md'
        - StoneCutterManager: 'vanilla/api/managers/StoneCutterManager.md'
      - Mod:
        - ModInfo: 'vanilla/api/mods/ModInfo.md'
        - Mod: 'vanilla/api/mods/Mods.md'
      - Pozioni:
        - MCPozione: 'vanilla/api/pozioni/MCPotion.m'
        - MCPotionEffect: 'vanilla/api/pozioni/MCPotionEffect.md'
        - MCPotionEffectInstance: 'vanilla/api/pozioni/MCPotionEffectInstance.md'
      - Ricetta:
        - RecipeFilter: 'vanilla/api/recipe/RecipeFilter.md'
        - RecipeFunctionArray: 'vanilla/api/recipe/RecipeFunctionArray.md'
        - RecipeFunctionMatrix: 'vanilla/api/recipe/RecipeFunctionMatrix.md'
        - RecipeFunctionSingle: 'vanilla/api/recipe/RecipeFunctionSingle.md'
      - Tags:
        - MCTag: 'vanilla/api/tags/MCTag.md'
      - Util:
        - BlockPos: 'vanilla/api/util/BlockPos.md'
        - Direzione: 'vanilla/api/util/Direction.md'
        - DirectionAxis: 'vanilla/api/util/DirectionAxis.md'
        - MCResourceLocation: 'vanilla/api/util/MCResourceLocation.md'
        - Testo:
          - MCStyle: 'vanilla/api/util/text/MCStyle.md'
          - MCTextComponent: 'vanilla/api/util/text/MCTextComponent.md'
      - Mondo:
        - MCBiome: 'vanilla/api/world/MCBiome.md'

- Crafttweaker:
    - Api:
      - Articolo:
        - Suggerimento:
          - ITooltipFunzione: 'crafttweaker/api/item/tooltip/ITooltipFunction.m'
      - Ricette:
        - WrapperRecipe: 'crafttweaker/api/recipes/WrapperRecipe.md'
      - Testo:
        - TextFormatting: 'crafttweaker/api/text/TextFormatting.md'

