- Mods:
    - Contenttweaker:
      - API:
        - BracketHandlers: 'mods/contenttweaker/API/BracketHandlers.md'
        - Api:
          - IIsBuilder: 'mods/contenttweaker/API/api/IIsBuilder.md'
        - Block:
          - BlockBuilder: 'mods/contenttweaker/API/block/BlockBuilder.md'
          - BlockTypeBuilder: 'mods/contenttweaker/API/block/BlockTypeBuilder.md'
          - Basic:
            - BlockBuilderBasic: 'mods/contenttweaker/API/block/basic/BlockBuilderBasic.md'
          - Pillar:
            - BlockBuilderPillarRotatable: 'mods/contenttweaker/API/block/pillar/BlockBuilderPillarRotatable.md'
          - Stairs:
            - BlockBuilderStairs: 'mods/contenttweaker/API/block/stairs/BlockBuilderStairs.md'
        - Item:
          - ItemBuilder: 'mods/contenttweaker/API/item/ItemBuilder.md'
          - ItemTypeBuilder: 'mods/contenttweaker/API/item/ItemTypeBuilder.md'
          - MCItemGroup: 'mods/contenttweaker/API/item/MCItemGroup.md'
          - MCToolType: 'mods/contenttweaker/API/item/MCToolType.md'
          - Basic:
            - ItemBuilderBasic: 'mods/contenttweaker/API/item/basic/ItemBuilderBasic.md'
          - Tool:
            - ItemBuilderTool: 'mods/contenttweaker/API/item/tool/ItemBuilderTool.md'

- Vanilla:
    - Api:
      - Block:
        - Material:
          - MCMaterial: 'vanilla/api/block/material/MCMaterial.md'
          - MCMaterialColor: 'vanilla/api/block/material/MCMaterialColor.md'
      - Blocks:
        - MCBlock: 'vanilla/api/blocks/MCBlock.md'
        - MCBlockState: 'vanilla/api/blocks/MCBlockState.md'
      - Brackets:
        - CommandStringDisplayable: 'vanilla/api/brackets/CommandStringDisplayable.md'
      - Util:
        - MCResourceLocation: 'vanilla/api/util/MCResourceLocation.md'

